name: table_calendar_null_safe
description: Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
version: 1.0.0
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
